import assert from 'node:assert/strict';import {assessment,newState,ingest,reserve,record,answer,canonical,easternDay} from '../worker/logic.mjs';
const state=newState();state.resume={bytes:40678};state.profile={facts:{citizenship:{verified:true,value:'US citizen',source:'User confirmed'}},evidence:[{id:'cloud',text:'Verified résumé cloud evidence'}]};
const good={title:'Lead Cloud Architect',company:'Example',url:'https://example.org/job/1?utm_source=test',criteria:[{requirement:'Cloud architecture',mandatory:true,matched:true,evidenceId:'cloud',quote:'Cloud architecture required'}],questions:[{label:'Citizenship',factKey:'citizenship',required:true}],route:{type:'ats'},verification:{originalVerified:true,originalUrl:'https://example.org/job/1',checkedAt:new Date().toISOString(),active:true,c2c:true,remoteCT:true,noTravel:true,hoursCompatible:true,currency:'USD',unit:'hour',minimumRate:125,termsEvidence:'Posting: remote US C2C $125/hour, no travel, 40 hours',criteriaComplete:true,questionsReviewed:true}};
assert.equal(ingest(state,[good]),1);assert.equal(ingest(state,[{...good,url:'https://example.org/job/1?utm_source=other'}]),0);let j=state.jobs[0];assert.equal(assessment(j,state).ready,true);assert.equal(assessment(j,state).score,100);
for(const change of [{minimumRate:100},{minimumRate:90},{unit:'year'},{currency:'CAD'},{c2c:false},{remoteCT:false},{noTravel:false},{criteriaComplete:false},{questionsReviewed:false},{checkedAt:'2020-01-01T00:00:00Z'},{checkedAt:'invalid'}])assert.equal(assessment({...j,verification:{...j.verification,...change}},state).ready,false,JSON.stringify(change));
assert.equal(assessment({...j,criteria:[{...j.criteria[0],evidenceId:'imaginary'}]},state).ready,false);assert.equal(assessment({...j,questions:[{label:'References',required:true}]},state).ready,false);assert.equal(answer({factKey:'unknown'},state.profile).supported,false);
const claim=reserve(state,j.id);assert.throws(()=>reserve(state,j.id),/submitted or reserved/);assert.throws(()=>record(state,j.id,{status:'ats_received',claimToken:claim.token}),/evidence/);assert.throws(()=>record(state,j.id,{status:'email_sent',claimToken:claim.token,evidence:{kind:'gmail_sent',reference:'test',verifiedAt:new Date().toISOString(),conditional:true}}),/Conditional/);record(state,j.id,{status:'ats_received',claimToken:claim.token,evidence:{kind:'ats_receipt',reference:'receipt',verifiedAt:new Date().toISOString()}});assert.throws(()=>reserve(state,j.id),/submitted or reserved/);
assert.equal(canonical('https://example.org/job?utm_source=a#apply'),'https://example.org/job');assert.equal(easternDay(new Date('2026-10-11T01:00:00Z')),'2026-10-10');assert.equal(assessment(j,state).interviewProbability,null);console.log('Eligibility, rate units, mandatory gaps, supported answers, duplicate submission, evidence and Eastern-day tests passed');

const filtering=newState();ingest(filtering,[{title:'Principal engineer',company:'Salary company',url:'https://example.org/salary',engagement:'Full-Time',location:'USA'},{title:'Architect',company:'European company',url:'https://example.org/eu',engagement:'Contract',location:'Germany'}]);assert(filtering.jobs.every(j=>j.status==='excluded'));assert.throws(()=>reserve(filtering,filtering.jobs[0].id),/submitted or reserved/);console.log('Known salary/foreign exclusions do not qualify or count as contract candidates');
