// Build script inlines logic, the dashboard, and retained static website assets.
import {defaults,easternDay,plain,canonical,newState,assessment,answer,ingest,candidate,preliminary,reserve,record} from './logic.mjs';
const STATE='primary';
const json=(v,status=200)=>new Response(JSON.stringify(v),{status,headers:{'content-type':'application/json','cache-control':'no-store','x-content-type-options':'nosniff'}});
async function read(env){if(!env.DB)throw Error('Database binding unavailable');const row=await env.DB.prepare('SELECT revision,payload FROM job_assistant_state WHERE id=?').bind(STATE).first();return row?{state:JSON.parse(row.payload),revision:row.revision}:{state:newState(),revision:null};}
async function change(env,fn){for(let i=0;i<6;i++){const {state,revision}=await read(env);const result=fn(state);state.updatedAt=new Date().toISOString();const q=revision===null?env.DB.prepare('INSERT INTO job_assistant_state (id,revision,payload) VALUES (?,0,?) ON CONFLICT(id) DO NOTHING').bind(STATE,JSON.stringify(state)):env.DB.prepare('UPDATE job_assistant_state SET payload=?,revision=revision+1 WHERE id=? AND revision=?').bind(JSON.stringify(state),STATE,revision);const r=await q.run();if(r.meta.changes)return result;}throw Error('Concurrent update; retry safely');}
async function remoteJSON(url){const r=await fetch(url,{headers:{'User-Agent':'InternetApps Job Assistant/1.0','Accept':'application/json'},signal:AbortSignal.timeout(18000)});if(!r.ok)throw Error('HTTP '+r.status);return r.json();}
const relevant=j=>/architect|principal.*engineer|cloud.*engineer|senior.*(java|\.net|software|integration).*|lead.*(software|platform)/i.test(j.title);
async function crawl(env){const day=easternDay();const {state}=await read(env);let lock;
 await change(env,s=>{const prior=s.runs.find(r=>r.day===day&&r.kind==='feeds');if(prior&&prior.status==='complete'){lock={cached:true,run:prior};return;}if(prior?.status==='running'&&Date.now()-Date.parse(prior.startedAt)<120000)throw Error('Discovery is already running');const run={id:crypto.randomUUID(),kind:'feeds',day,startedAt:new Date().toISOString(),status:'running',sources:[],newLeads:0};s.runs=s.runs.filter(r=>!(r.day===day&&r.kind==='feeds'));s.runs.push(run);s.runs=s.runs.slice(-120);lock={run};});if(lock.cached)return lock;
 const sources=[{name:'Remotive',url:'https://remotive.com/api/remote-jobs?category=software-dev',map:d=>(d.jobs||[]).map(j=>({title:j.title,company:j.company_name,url:j.url,description:j.description,salary:j.salary||'Not disclosed',engagement:j.job_type,location:j.candidate_required_location,publishedAt:j.publication_date,source:'Remotive',route:{type:'ats',url:j.url},attribution:'Remotive public API; listings delayed 24 hours'}))},{name:'Jobicy',url:'https://jobicy.com/api/v2/remote-jobs?count=100&industry=engineering',map:d=>(d.jobs||[]).map(j=>({title:j.jobTitle,company:j.companyName,url:j.url,description:j.jobDescription,salary:j.salaryMin?`${j.salaryCurrency} ${j.salaryMin}–${j.salaryMax} / ${j.salaryPeriod}`:'Not disclosed',engagement:(j.jobType||[]).join(', '),location:j.jobGeo,publishedAt:j.pubDate,source:'Jobicy',route:{type:'ats',url:j.url}}))}];
 for(const board of state.settings.greenhouseBoards||[])sources.push({name:'Greenhouse / '+board,url:'https://boards-api.greenhouse.io/v1/boards/'+encodeURIComponent(board)+'/jobs?content=true',map:d=>(d.jobs||[]).map(j=>({title:j.title,company:board,url:j.absolute_url,description:j.content,location:j.location?.name,source:'Greenhouse employer board',requisitionId:String(j.id),salary:'Not disclosed',route:{type:'ats',url:j.absolute_url}}))});
 const results=await Promise.allSettled(sources.map(async source=>{const data=await remoteJSON(source.url);return {name:source.name,jobs:source.map(data).filter(relevant),url:source.url};}));
 return change(env,s=>{const run=s.runs.find(r=>r.id===lock.run.id);if(!run)throw Error('Run replaced; retry');results.forEach((r,i)=>{if(r.status==='fulfilled'){const before=s.jobs.length;ingest(s,r.value.jobs,r.value.name);const added=s.jobs.slice(before);run.newLeads+=added.filter(j=>j.status!=='excluded').length;run.screened=(run.screened||0)+r.value.jobs.length;run.sources.push({name:r.value.name,url:r.value.url,status:'ok',relevant:r.value.jobs.length,added:added.filter(j=>j.status!=='excluded').length,excluded:added.filter(j=>j.status==='excluded').length});}else run.sources.push({name:sources[i].name,status:'error',error:String(r.reason.message||r.reason)});});run.status='complete';run.finishedAt=new Date().toISOString();run.shortfall=Math.max(0,s.settings.dailyTarget-s.jobs.filter(j=>j.discoveredDay===day&&!j.historical&&j.status!=='excluded').length);run.note=run.shortfall?'Continue broad employer/recruiter search; '+run.shortfall+' more new relevant leads needed.':'Discovery target met; qualification verification remains separate.';return {run};});
}
async function api(request,env,path){if(request.method!=='GET'){const origin=request.headers.get('origin');if(origin&&origin!==new URL(request.url).origin)return json({error:'Cross-origin write rejected'},403);if(Number(request.headers.get('content-length')||0)>2000000)return json({error:'Request too large'},413);}
 if(path==='/api/jobs/state'&&request.method==='GET'){const {state}=await read(env);const day=easternDay();return json({...state,today:day,jobs:state.jobs.map(j=>({...j,assessment:assessment(j,state),preliminary:preliminary(j),answers:(j.questions||[]).map(q=>({...q,...answer(q,state.profile)}))})),stats:{discovered:state.jobs.filter(j=>j.discoveredDay===day&&!j.historical&&j.status!=='excluded').length,ready:state.jobs.filter(j=>assessment(j,state).ready&&!['email_sent','ats_received','interview','accepted','claimed','prior_application','excluded'].includes(j.status)).length,submittedToday:state.jobs.filter(j=>j.events.some(e=>['email_sent','ats_received'].includes(e.type)&&easternDay(new Date(e.at))===day)).length,held:state.jobs.filter(j=>!assessment(j,state).ready&&!['email_sent','ats_received','interview','accepted','prior_application','excluded'].includes(j.status)).length}});}
 if(path==='/api/jobs/resume'&&request.method==='GET'){const f=await env.BUCKET.get('applicant/resume.docx');return f?new Response(f.body,{headers:{'content-type':'application/vnd.openxmlformats-officedocument.wordprocessingml.document','content-disposition':'attachment; filename="Principal_Architect_Resume.docx"','cache-control':'no-store'}}):json({error:'No résumé uploaded'},404);}
 if(path==='/api/jobs/resume'&&request.method==='PUT'){const bytes=await request.arrayBuffer();if(bytes.byteLength>1000000||bytes.byteLength<100||new Uint8Array(bytes)[0]!==80||new Uint8Array(bytes)[1]!==75)return json({error:'Upload the existing DOCX résumé (max 1 MB)'},400);await env.BUCKET.put('applicant/resume.docx',bytes,{httpMetadata:{contentType:'application/vnd.openxmlformats-officedocument.wordprocessingml.document'}});await change(env,s=>s.resume={filename:'Principal_Architect_Resume.docx',bytes:bytes.byteLength,uploadedAt:new Date().toISOString()});return json({uploaded:true});}
 if(request.method!=='POST')return json({error:'Route not found'},404);
 if(path==='/api/jobs/run')return json(await crawl(env));
 const b=await request.json();
 if(path==='/api/jobs/import'){if(!Array.isArray(b.jobs)||b.jobs.length>100)return json({error:'Import up to 100 jobs'},400);return json(await change(env,s=>({added:ingest(s,b.jobs)})));}
 if(path==='/api/jobs/profile'){if(!b.facts||!Array.isArray(b.evidence))throw Error('Verified facts and résumé evidence are required');return json(await change(env,s=>{s.profile={facts:b.facts,evidence:b.evidence};return {saved:true};}));}
 if(path==='/api/jobs/settings'){const patch={};if(b.matchThreshold!==undefined){if(Number(b.matchThreshold)<90||Number(b.matchThreshold)>100)throw Error('Match threshold must be 90–100');patch.matchThreshold=Number(b.matchThreshold);}if(b.dailyTarget!==undefined){if(Number(b.dailyTarget)<10||Number(b.dailyTarget)>100)throw Error('Daily target must be 10–100');patch.dailyTarget=Number(b.dailyTarget);}for(const k of ['linkedin','indeed','autoApply'])if(b[k]!==undefined)patch[k]=!!b[k];if(b.greenhouseBoards){if(!Array.isArray(b.greenhouseBoards)||b.greenhouseBoards.length>15||b.greenhouseBoards.some(x=>! /^[a-z0-9_-]{1,80}$/i.test(x)))throw Error('Use up to 15 valid employer board names');patch.greenhouseBoards=b.greenhouseBoards;}return json(await change(env,s=>{Object.assign(s.settings,patch);return {saved:true};}));}
 if(path==='/api/jobs/answer')return json(await change(env,s=>{const j=s.jobs.find(x=>x.id===b.id);const q=j?.questions?.[b.questionIndex];if(!q||typeof b.value!=='string'||!b.value.trim())throw Error('Question and nonempty answer required');const key='answer:'+j.id+':'+b.questionIndex;s.profile.facts[key]={value:b.value.trim(),verified:true,source:'User entered in private Job Assistant at '+new Date().toISOString()};q.factKey=key;return {saved:true};}));
 if(path==='/api/jobs/review')return json(await change(env,s=>{const j=s.jobs.find(x=>x.id===b.id);if(!j)throw Error('Job not found');if(['claimed','email_sent','ats_received','interview','accepted'].includes(j.status))throw Error('Submitted or reserved jobs cannot be rewritten');for(const k of ['verification','criteria','questions','route','nextStep'])if(b[k]!==undefined)j[k]=b[k];const a=assessment(j,s);j.status=a.ready?'ready':'review';j.events.push({at:new Date().toISOString(),type:'reviewed',score:a.score,reasons:a.reasons});return {assessment:a};}));
 if(path==='/api/jobs/queue')return json(await change(env,s=>{let count=0;for(const j of s.jobs)if(assessment(j,s).ready&&['ready','review','queued'].includes(j.status)){j.status='queued';j.nextStep='Daily assistant: verify Gmail duplicates, answer supported questions, submit and save receipt';count++;}return {queued:count};}));
 if(path==='/api/jobs/claim')return json(await change(env,s=>reserve(s,b.id)));
 if(path==='/api/jobs/event')return json(await change(env,s=>record(s,b.id,b)));
 if(path==='/api/jobs/release')return json(await change(env,s=>{const j=s.jobs.find(x=>x.id===b.id);if(!j||!j.claim||j.claim.token!==b.claimToken)throw Error('Reservation token required');j.status='blocked';j.claim=null;j.nextStep=b.reason||'Verify whether a submission happened before retrying';return {released:true};}));
 return json({error:'Route not found'},404);
}
export default {async fetch(request,env){const path=new URL(request.url).pathname;try{if(path.startsWith('/api/jobs/'))return await api(request,env,path);if(path==='/jobs'||path==='/jobs/'||path==='/job-crawler.html')return new Response(APP_HTML,{headers:{'content-type':'text/html; charset=utf-8','cache-control':'no-store','x-robots-tag':'noindex, nofollow'}});let key=path==='/'?'/index.html':path;if(key.endsWith('/'))key+='index.html';if(key.startsWith('/dist/'))key=key.slice(5);const asset=STATIC_ASSETS[key];if(!asset)return new Response('Not found',{status:404});const bytes=Uint8Array.from(atob(asset.data),c=>c.charCodeAt(0));return new Response(bytes,{headers:{'content-type':asset.type,'x-content-type-options':'nosniff'}});}catch(e){return json({error:String(e.message||e)},400);}}};

